### ISSUE TITLE
To saturate the dynamics or not to saturate the dynamics, that is the question

### ISSUE THREAD

**Issue by carsonwmoon** [randybeard/controlbook_public#5]
The answer key we provide for DEF dynamics don't saturate the inputs before doing RK4, but the provided files (arm_dynamics for example) do. The test cases provided don't. So do we want to saturate the inputs before doing dynamics, or no?

**Comment by BenA8** [comment]
I think we should saturate the force in dynamics, since that's what the actual hardware would do: if you tell the hardware to input a force that is physically too big for it, then it will do the best it can.
